#!/usr/bin/env bash

if [ ! -e ~/.zshrc ]; then
  ln -s ~/.code/zsh/zshrc ~/.zshrc
fi

if [ ! -d ~/.config ]; then
  mkdir -p ~/.config
fi

if [ ! -e ~/.local/share/nvim/site/autoload/plug.vim ]; then
  # Install neovim config and vim-plug
  curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

if [ ! -e ~/.config/nvim ]; then
  ln -s ~/.code/nvim ~/.config/nvim
fi

if [ ! -e ~/.tmux.conf ]; then
  ln -s ~/.code/tmux.conf ~/.tmux.conf
fi
