call plug#begin('~/.vim/plugged')

	Plug 'scrooloose/nerdtree'
	Plug 'kien/ctrlp.vim'
	Plug 'vim-ruby/vim-ruby'
	Plug 'tpope/vim-rails'
	Plug 'tpope/vim-haml'
	Plug 'othree/html5.vim'
	Plug 'scrooloose/syntastic'
	Plug 'jlanzarotta/bufexplorer'
	Plug 'altercation/vim-colors-solarized'

  Plug 'neoclide/coc.nvim', {'branch': 'release'}
  Plug 'elixir-editors/vim-elixir'
  Plug 'mhinz/vim-mix-format'
  Plug 'tpope/vim-fugitive'
call plug#end()

execute 'source' '~/.code/vim/settings.vim'
for fpath in split(globpath('~/.code/vim/settings', '*.vim'), '\n')
  execute 'source' fpath
endfor
