export ZSH=$HOME/.code/zsh

plugins=(code git ruby rust docker nvm)
source $ZSH/init.zsh

export PATH="/usr/local/bin:$PATH"

if type mvim > /dev/null 2>&1; then
  alias m="mvim $@ > /dev/null 2>&1"
  alias v="mvim -v"
  alias vim="mvim -v"
  export EDITOR="mvim -v"
else
  alias v="vim"
  alias n="nvim"
  export EDITOR="vim"
fi

if type ccat > /dev/null 2>&1; then
  alias cat=ccat
fi

if type thefuck > /dev/null 2>&1; then
  eval $(thefuck --alias)
fi

if type direnv > /dev/null 2>&1; then
  eval "$(direnv hook zsh)"
fi

case $TERM in
    xterm*)
        precmd () {print -Pn "\e]0;%~\a"}
        ;;
esac

export NODE_TLS_REJECT_UNAUTHORIZED=0
export GOPATH="${HOME}/gocode"

if type brew > /dev/null 2>&1; then
  export GOROOT="$(brew --prefix)/opt/go/libexec"
fi

if [ -f $HOME/.localrc ]; then
  source $HOME/.localrc
fi

