export ZSH=$HOME/.code/zsh

plugins=(code git mix ruby rust docker)
source $ZSH/init.zsh

export PATH="/usr/local/bin:$PATH"

if type mvim > /dev/null 2>&1; then
  alias m="mvim $@ > /dev/null 2>&1"
  alias v="mvim -v"
  alias vim="mvim -v"
  export EDITOR="mvim -v"
else
  alias v="vim"
  export EDITOR="vim"
fi

if type thefuck > /dev/null 2>&1; then
  eval $(thefuck --alias)
fi

case $TERM in
    xterm*)
        precmd () {print -Pn "\e]0;%~\a"}
        ;;
esac

export NODE_TLS_REJECT_UNAUTHORIZED=0
export GOPATH="${HOME}/gocode"

if type brew > /dev/null 2>&1; then
  export GOROOT="$(brew --prefix golang)/libexec"
  . $(brew --prefix asdf)/asdf.sh
  . $(brew --prefix asdf)/etc/bash_completion.d/asdf.bash
fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH=$PATH:$GOPATH/bin:$GOROOT/bin
export PATH=$PATH:$HOME/.cargo/bin
export PATH=$PATH:$HOME/.mix/escripts
export PATH=$PATH:$HOME/.rvm/bin

# Enable shell history for IEX
# https://til.hashrocket.com/posts/is9yfvhdnp-enable-history-in-iex-through-erlang-otp-20-
export ERL_AFLAGS="-kernel shell_history enabled"

export PATH="/usr/local/opt/openssl/bin:$HOME/bin:$PATH"
